workflows:
  ios-release-workflow:
    name: PraxiaOne iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: praxia_mobile_app
    environment:
      flutter: stable
      xcode: 26.2 
    scripts:
      - name: Prepare Flutter
        script: |
          flutter pub get
          flutter precache --ios
          # This command creates the 'podhelper.rb' file that the Podfile needs
          flutter build ios --config-only --no-codesign
      - name: Install CocoaPods
        script: |
          cd ios
          # Force a fresh install of the plugins
          rm -rf Pods
          rm -f Podfile.lock
          pod install
      - name: Build IPA
        script: |
          # The --no-codesign is key for testing
          flutter build ipa --release --no-codesign -t lib/main.dart
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - omkarambar@gmail.com
          