// lib/ui/screens/action_plan_screen.dart
// Screen 4 — Action Plan
// Displays personalized action items generated by DeepSeek.
// Allows CRUD operations on action items.

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../lab_ai/lab_models.dart';
import 'track_progress_screen.dart';

class ActionPlanScreen extends StatefulWidget {
  final LabInsightsResponse response;

  const ActionPlanScreen({Key? key, required this.response}) : super(key: key);

  @override
  State<ActionPlanScreen> createState() => _ActionPlanScreenState();
}

class _ActionPlanScreenState extends State<ActionPlanScreen> {
  late List<ActionPlanItem> _actions;

  @override
  void initState() {
    super.initState();
    _actions = List.from(widget.response.actionPlan);
  }

  IconData _getIconData(String sfSymbolHint) {
    final s = sfSymbolHint.toLowerCase();
    if (s.contains('walk') || s.contains('figure')) return Icons.directions_walk_rounded;
    if (s.contains('food') || s.contains('fork') || s.contains('diet')) return Icons.restaurant_rounded;
    if (s.contains('sleep') || s.contains('moon')) return Icons.bedtime_rounded;
    if (s.contains('drop') || s.contains('water')) return Icons.water_drop_rounded;
    if (s.contains('pill') || s.contains('med')) return Icons.medication_rounded;
    if (s.contains('heart')) return Icons.favorite_rounded;
    return Icons.task_alt_rounded;
  }

  void _showDetailSheet(BuildContext context, ActionPlanItem action) {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(24))),
      builder: (context) => Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(color: const Color(0xFFEFF6FF), borderRadius: BorderRadius.circular(12)),
                  child: Icon(_getIconData(action.icon), color: const Color(0xFF2563EB), size: 28),
                ),
                const SizedBox(width: 16),
                Expanded(child: Text(action.title, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w800, color: Color(0xFF1E293B)))),
              ],
            ),
            const SizedBox(height: 20),
            Text(action.description, style: const TextStyle(fontSize: 15, color: Color(0xFF475569), height: 1.5)),
            const SizedBox(height: 32),
            SizedBox(
              width: double.infinity,
              height: 50,
              child: ElevatedButton(
                onPressed: () => Navigator.pop(context),
                style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF1E3A8A), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)), elevation: 0),
                child: const Text('Got it', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w700, fontSize: 16)),
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _showEditDialog({ActionPlanItem? action, int? index}) {
    final titleController = TextEditingController(text: action?.title ?? '');
    final descController = TextEditingController(text: action?.description ?? '');

    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: Text(action == null ? 'New Action' : 'Edit Action', style: const TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF1D3B5A))),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              controller: titleController,
              decoration: const InputDecoration(labelText: 'Action Title', border: OutlineInputBorder()),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: descController,
              maxLines: 3,
              decoration: const InputDecoration(labelText: 'Description', border: OutlineInputBorder()),
            ),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancel', style: TextStyle(color: Colors.grey))),
          ElevatedButton(
            onPressed: () {
              if (titleController.text.isEmpty) return;
              final newItem = ActionPlanItem(
                id: action?.id ?? DateTime.now().millisecondsSinceEpoch,
                icon: action?.icon ?? 'star',
                title: titleController.text,
                description: descController.text,
                isActive: action?.isActive ?? false,
              );
              setState(() {
                if (index != null) {
                  _actions[index] = newItem;
                } else {
                  _actions.add(newItem);
                }
              });
              Navigator.pop(ctx);
            },
            style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF2563EB)),
            child: const Text('Save', style: TextStyle(color: Colors.white)),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF2F4F7),
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, color: Color(0xFF1D3B5A), size: 20),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Padding(
              padding: EdgeInsets.fromLTRB(20, 10, 20, 24),
              child: Text(
                'Your Top Actions',
                style: TextStyle(fontSize: 28, fontWeight: FontWeight.w900, color: Color(0xFF1E293B)),
              ),
            ),
            Expanded(
              child: ListView.builder(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                itemCount: _actions.length + 1,
                itemBuilder: (context, index) {
                  if (index == _actions.length) {
                    return Padding(
                      padding: const EdgeInsets.only(top: 16, bottom: 32),
                      child: Center(
                        child: TextButton(
                          onPressed: () => _showEditDialog(),
                          child: const Text('+ Add more actions', style: TextStyle(color: Color(0xFF2563EB), fontWeight: FontWeight.w700, fontSize: 15)),
                        ),
                      ),
                    );
                  }

                  final action = _actions[index];
                  return Container(
                    margin: const EdgeInsets.only(bottom: 12),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(16),
                      boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 10, offset: const Offset(0, 4))],
                    ),
                    child: Material(
                      color: Colors.transparent,
                      child: InkWell(
                        borderRadius: BorderRadius.circular(16),
                        onTap: () => _showDetailSheet(context, action),
                        child: Padding(
                          padding: const EdgeInsets.all(16),
                          child: Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.all(12),
                            decoration: BoxDecoration(color: const Color(0xFFEFF6FF), borderRadius: BorderRadius.circular(12)),
                            child: Icon(_getIconData(action.icon), color: const Color(0xFF2563EB), size: 24),
                          ),
                          const SizedBox(width: 16),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(action.title, style: const TextStyle(fontWeight: FontWeight.w800, fontSize: 16, color: Color(0xFF1E293B))),
                                const SizedBox(height: 4),
                                Text(action.description, style: const TextStyle(fontSize: 13, color: Color(0xFF64748B)), maxLines: 2, overflow: TextOverflow.ellipsis),
                              ],
                            ),
                          ),
                          const SizedBox(width: 8),
                          Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                decoration: BoxDecoration(
                                  color: action.isActive ? const Color(0xFFD1FAE5) : const Color(0xFFF1F5F9),
                                  borderRadius: BorderRadius.circular(8),
                                ),
                                child: Text(
                                  action.isActive ? 'Active' : 'Inactive',
                                  style: TextStyle(
                                    fontSize: 10,
                                    fontWeight: FontWeight.bold,
                                    color: action.isActive ? const Color(0xFF059669) : const Color(0xFF64748B),
                                  ),
                                ),
                              ),
                              const SizedBox(height: 6),
                              PopupMenuButton<String>(
                                icon: const Icon(Icons.more_vert_rounded, color: Color(0xFF94A3B8), size: 24),
                                onSelected: (value) async {
                                  if (value == 'edit') {
                                    _showEditDialog(action: action, index: index);
                                  } else if (value == 'delete') {
                                    setState(() => _actions.removeAt(index));
                                  } else if (value == 'toggleActive') {
                                    final prefs = await SharedPreferences.getInstance();
                                    final bool willBeActive = !action.isActive;
                                    if (action.id != null) {
                                      if (willBeActive) {
                                        await prefs.setBool('plan_active_${action.id}', true);
                                      } else {
                                        await prefs.remove('plan_active_${action.id}');
                                      }
                                    }
                                    setState(() {
                                      _actions[index] = ActionPlanItem(
                                        id: action.id,
                                        icon: action.icon,
                                        title: action.title,
                                        description: action.description,
                                        isActive: willBeActive,
                                      );
                                    });
                                  }
                                },
                                itemBuilder: (BuildContext context) => <PopupMenuEntry<String>>[
                                  PopupMenuItem<String>(
                                    value: 'toggleActive',
                                    child: ListTile(
                                      leading: Icon(action.isActive ? Icons.cancel : Icons.check_circle, color: action.isActive ? Colors.orange : Colors.green),
                                      title: Text(action.isActive ? 'Deactivate' : 'Activate Plan'),
                                      contentPadding: EdgeInsets.zero,
                                    ),
                                  ),
                                  const PopupMenuItem<String>(
                                    value: 'edit',
                                    child: ListTile(
                                      leading: Icon(Icons.edit, color: Colors.blue),
                                      title: Text('Edit Action'),
                                      contentPadding: EdgeInsets.zero,
                                    ),
                                  ),
                                  const PopupMenuItem<String>(
                                    value: 'delete',
                                    child: ListTile(
                                      leading: Icon(Icons.delete, color: Colors.red),
                                      title: Text('Delete Action'),
                                      contentPadding: EdgeInsets.zero,
                                    ),
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              );
            },
              ),
            ),
            Container(
              color: Colors.white,
              padding: const EdgeInsets.fromLTRB(16, 12, 16, 24),
              child: SizedBox(
                width: double.infinity,
                height: 54,
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const TrackProgressScreen()));
                    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Action plan tracking started!'), backgroundColor: Color(0xFF10B981)));
                  },
                  style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF1E3A8A), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)), elevation: 0),
                  child: const Text('Start Tracking', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w700, fontSize: 16)),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
