# Generated by Django 6.0.2 on 2026-03-05 13:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChronicDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_type",
                    models.CharField(
                        choices=[
                            ("type2_diabetes", "Type 2 Diabetes"),
                            ("hypertension", "Hypertension (High Blood Pressure)"),
                            ("coronary_artery_disease", "Coronary Artery Disease"),
                            ("copd", "COPD (Chronic Obstructive Pulmonary Disease)"),
                            ("asthma", "Asthma"),
                            ("chronic_kidney_disease", "Chronic Kidney Disease"),
                            ("heart_failure", "Heart Failure"),
                            ("arthritis", "Arthritis"),
                            ("depression", "Depression"),
                            ("obesity", "Obesity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("disease_name", models.CharField(max_length=255)),
                ("diagnosis_date", models.DateField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("critical", "Critical"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("clinical_notes", models.JSONField(blank=True, default=dict)),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("last_risk_assessment", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chronic_diseases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CareGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_title", models.CharField(max_length=255)),
                ("goal_description", models.TextField()),
                ("target_value", models.FloatField()),
                ("current_value", models.FloatField(default=0.0)),
                ("unit", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("achieved", "Achieved"),
                            ("failed", "Failed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("target_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_goals",
                        to="chronic_mgmt.chronicdisease",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold Exceeded"),
                            ("trend", "Trend Alert"),
                            ("medication", "Medication Reminder"),
                            ("appointment", "Appointment Reminder"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metric_type", models.CharField(max_length=100)),
                ("threshold_min", models.FloatField(blank=True, null=True)),
                ("threshold_max", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notify_user", models.BooleanField(default=True)),
                ("notify_doctor", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="chronic_mgmt.chronicdisease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiseaseMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_type", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("reference_min", models.FloatField(blank=True, null=True)),
                ("reference_max", models.FloatField(blank=True, null=True)),
                (
                    "measured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="chronic_mgmt.chronicdisease",
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="DiseaseTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("diagnosis", "Diagnosis"),
                            ("hospitalization", "Hospitalization"),
                            ("medication_change", "Medication Change"),
                            ("procedure", "Medical Procedure"),
                            ("milestone", "Major Milestone"),
                            ("complication", "Complication"),
                            ("remission", "Remission"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_title", models.CharField(max_length=255)),
                ("event_description", models.TextField()),
                ("event_date", models.DateField()),
                (
                    "impact_level",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        max_length=50,
                    ),
                ),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="chronic_mgmt.chronicdisease",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(max_length=255)),
                ("generic_name", models.CharField(blank=True, max_length=255)),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "adherence_percentage",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("side_effects", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("started_date", models.DateField(default=django.utils.timezone.now)),
                ("ended_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="chronic_mgmt.chronicdisease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                ("contributing_factors", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("grounding_evidence", models.TextField(blank=True)),
                ("sources", models.JSONField(default=list)),
                ("assessment_date", models.DateTimeField(auto_now_add=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessments",
                        to="chronic_mgmt.chronicdisease",
                    ),
                ),
            ],
            options={
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="chronicdisease",
            index=models.Index(
                fields=["user", "disease_type"], name="chronic_mgm_user_id_be53f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chronicdisease",
            index=models.Index(
                fields=["user", "is_active"], name="chronic_mgm_user_id_b503f9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chronicdisease",
            unique_together={("user", "disease_type")},
        ),
        migrations.AddIndex(
            model_name="diseasemetric",
            index=models.Index(
                fields=["disease", "metric_type", "measured_at"],
                name="chronic_mgm_disease_40de5f_idx",
            ),
        ),
    ]
