platform :ios, '14.0'

# Standard Flutter path setup
# This assumes your Podfile is in praxia_mobile_app/ios/Podfile
flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # This ensures the iOS 14.0 target is forced onto every plugin
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end