platform :ios, '14.0'

# Use a relative path that points exactly to where Flutter stores its podhelper
load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # This is what was missing! It tells Xcode to include 'audio_session', 'health', etc.
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
