# Generated by Django 6.0.1 on 2026-01-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wellness_interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
