# Generated by Django 4.2 on 2026-03-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_userprofile_wellness_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadeddocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("care_plan", "Care Plan"),
                    ("lab_result", "Lab Result"),
                    ("insurance_policy", "Insurance Policy"),
                ],
                max_length=20,
            ),
        ),
    ]
