# Generated by Django 6.0.2 on 2026-03-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_uploadeddocument_doc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="raw_text_extracted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
