# Generated by Django 4.2 on 2026-04-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_medication"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
