# Generated by Django 4.2 on 2026-04-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
