# Generated by Django 4.2.8 on 2026-04-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
