# Generated by Django 4.2.8 on 2026-04-07 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_userprofile_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_email', models.CharField(blank=True, default='', max_length=255)),
                ('new_email', models.CharField(blank=True, default='', max_length=255)),
                ('old_username', models.CharField(blank=True, default='', max_length=255)),
                ('new_username', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
