# Generated by Django 4.2.8 on 2026-04-10 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0015_supportticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_ai_mode",
            field=models.CharField(default="Fast (Med42)", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="privacy_lock_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="PaymentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_provider",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "policy_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_four_digits",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_alerts", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                ("appointment_reminders", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True, help_text="Comma-separated conditions", null=True
                    ),
                ),
                (
                    "medications_list",
                    models.TextField(
                        blank=True, help_text="Comma-separated medications", null=True
                    ),
                ),
                (
                    "allergies_list",
                    models.TextField(
                        blank=True, help_text="Comma-separated allergies", null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
