# Generated by Django 4.2.8 on 2026-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_address_userprofile_preferred_ai_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
