# Generated by Django 4.2.8 on 2026-05-06 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_chatmessage_meta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtext', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(default='directions_walk', max_length=50)),
                ('status', models.CharField(default='Not Started', max_length=20)),
                ('status_color', models.CharField(default='error', max_length=20)),
                ('color_hex', models.CharField(default='#EF4444', max_length=10)),
                ('days_completed', models.JSONField(default=list)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_actionable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
