# Generated by Django 4.2.8 on 2026-05-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_actiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='latest_biomarkers',
            field=models.JSONField(blank=True, help_text='Latest parsed lab biomarkers', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='latest_insights',
            field=models.JSONField(blank=True, help_text='Latest AI generated insights', null=True),
        ),
    ]
